dist: trusty

# Use containers instead of full VMs for faster startup.
sudo: false

matrix:
    fast_finish: true

language: python

python:
    #- "3.0"
    - "3.3"
    - "3.4"
    #- "3.5"
    #- "3.6"

install:
    - pip install .

script:
    - pycli_path=$(python -c "import pycli; print(pycli.__path__[0])")
    - cd $pycli_path
    - python -m unittest discover tests
